import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Main from './components/Main'
import NavBar from './components/NavBar'
import {About} from "./components/About";

export default function Home() {
  return (
    <div >
      <Head>
        <title>Hamma | next-developper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Main />
      <About />
    </div>
  )
}
